version: '3.3'

services:
    node-app:
        build: .
        environment:
            - DATABASE_HOST=db
        depends_on:
            - db
        restart: always
        ports:
            - 3000:3000
    db:
        build: ./mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: testdb_two